<!DOCTYPE html>
<head>
  	<title><?php print $pageTitle ?> | 3Sided Projects</title>
  	<meta charset="utf-8">
	<meta name="description" content="<?php print $pageDescription ?>">
	<meta name="keywords" content="">
  	<meta name="viewport" content="width=device-width">
<!-- CSS -->
  	<link rel="shortcut icon" type="image/ico" href="favicon.ico">
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro' rel='stylesheet' type='text/css'>
	<link href="css/style.css" type="text/css" rel="stylesheet"/>

<!-- Javascript -->
	<script type="text/javascript" src="js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="js/freewall.js"></script>
    <script type="text/javascript" src="js/bucket.js"></script>

<!--[if lt IE 9]>
<script src="http://ie7-js.googlecode.com/svn/version/2.1(beta4)/IE9.js"></script>
<![endif]-->
</head>

<body>

<header>
	<div id="logo-container">
	</div>
	<nav>
		<ul id="menu">
			<li><a href="work.php">Work</a></li>
			<li><a href="about.php">About</a></li>
			<li><a href="contact.php">Contact</a></li>					
		</ul>
	</nav>			
</header>